theme: jekyll-theme-minimal

# Site settings
title: Chenfeng Huang's Portfolio
email: chengfengeric@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chenfeng Huang's personal portfolio and blog. 


plugins:
  - jekyll-remote-theme 


author:
  name: Chenfeng Huang
  email: chengfengeric@gmail.com


